[ 2024-12-10 21:50:42,709 ] werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.222.153:8080
[ 2024-12-10 21:50:42,709 ] werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2024-12-10 21:50:43,699 ] werkzeug - INFO - 127.0.0.1 - - [10/Dec/2024 21:50:43] "GET / HTTP/1.1" 200 -
[ 2024-12-10 21:50:45,928 ] root - INFO - Updated DATA_DOWNLOAD_URL to: https://drive.google.com/file/d/1ECfl3dtYyfivY8kYPq7RHUB-2vf61/view?usp=share_link
[ 2024-12-10 21:50:45,928 ] root - INFO - Training parameters - Epochs: 1, Batch Size: 16
[ 2024-12-10 21:50:45,931 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2024-12-10 21:50:45,931 ] root - INFO - Getting the data from URL
[ 2024-12-10 21:50:45,931 ] root - INFO - Entered initiate_data_ingestion method of Data_Ingestion class
[ 2024-12-10 21:50:45,932 ] root - INFO - Downloading data from https://drive.google.com/file/d/1ECfl3dtYyfivY8kYPq7RHUB-2vf61/view?usp=share_link into file artifacts\data_ingestion\data.zip
[ 2024-12-10 21:50:46,455 ] root - ERROR - Attempt 1 failed: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1ECfl3dtYyfivY8kYPq7RHUB-2vf61

but Gdown can't. Please check connections and permissions.
[ 2024-12-10 21:50:51,925 ] root - ERROR - Attempt 2 failed: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1ECfl3dtYyfivY8kYPq7RHUB-2vf61

but Gdown can't. Please check connections and permissions.
[ 2024-12-10 21:50:57,528 ] root - ERROR - Attempt 3 failed: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1ECfl3dtYyfivY8kYPq7RHUB-2vf61

but Gdown can't. Please check connections and permissions.
[ 2024-12-10 21:51:02,529 ] root - ERROR - Error during training: Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\pipeline\training_pipeline.py] line number [98] error message [Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\pipeline\training_pipeline.py] line number [37] error message [Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\components\data_ingestion.py] line number [108] error message [Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\components\data_ingestion.py] line number [74] error message ['NoneType' object has no attribute 'tb_frame']]]]
[ 2024-12-10 21:51:02,531 ] werkzeug - INFO - 127.0.0.1 - - [10/Dec/2024 21:51:02] "[35m[1mPOST /train HTTP/1.1[0m" 500 -
[ 2024-12-10 21:52:08,389 ] root - INFO - Updated DATA_DOWNLOAD_URL to: https://drive.google.com/file/d/1ECfl3dtYyfivY8kYPq7RHUB/view?usp=share_link
[ 2024-12-10 21:52:08,389 ] root - INFO - Training parameters - Epochs: 1, Batch Size: 16
[ 2024-12-10 21:52:08,389 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2024-12-10 21:52:08,389 ] root - INFO - Getting the data from URL
[ 2024-12-10 21:52:08,390 ] root - INFO - Entered initiate_data_ingestion method of Data_Ingestion class
[ 2024-12-10 21:52:08,392 ] root - INFO - Downloading data from https://drive.google.com/file/d/1ECfl3dtYyfivY8kYPq7RHUB/view?usp=share_link into file artifacts\data_ingestion\data.zip
[ 2024-12-10 21:52:09,080 ] root - ERROR - Attempt 1 failed: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1ECfl3dtYyfivY8kYPq7RHUB

but Gdown can't. Please check connections and permissions.
[ 2024-12-10 21:52:14,647 ] root - ERROR - Attempt 2 failed: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1ECfl3dtYyfivY8kYPq7RHUB

but Gdown can't. Please check connections and permissions.
[ 2024-12-10 21:52:20,147 ] root - ERROR - Attempt 3 failed: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1ECfl3dtYyfivY8kYPq7RHUB

but Gdown can't. Please check connections and permissions.
[ 2024-12-10 21:52:25,148 ] root - ERROR - Error during training: Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\pipeline\training_pipeline.py] line number [98] error message [Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\pipeline\training_pipeline.py] line number [37] error message [Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\components\data_ingestion.py] line number [108] error message [Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\components\data_ingestion.py] line number [74] error message ['NoneType' object has no attribute 'tb_frame']]]]
[ 2024-12-10 21:52:25,149 ] werkzeug - INFO - 127.0.0.1 - - [10/Dec/2024 21:52:25] "[35m[1mPOST /train HTTP/1.1[0m" 500 -
[ 2024-12-10 21:55:51,224 ] werkzeug - INFO - 127.0.0.1 - - [10/Dec/2024 21:55:51] "GET / HTTP/1.1" 200 -
[ 2024-12-10 21:55:51,485 ] werkzeug - INFO - 127.0.0.1 - - [10/Dec/2024 21:55:51] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[ 2024-12-10 21:56:29,443 ] root - INFO - Updated DATA_DOWNLOAD_URL to: https://drive.google.com/file/d/1Bl2r-dnEQzQle8eXc2j6_SNqOCTD18TN/view?usp=sharing
[ 2024-12-10 21:56:29,443 ] root - INFO - Training parameters - Epochs: 1, Batch Size: 16
[ 2024-12-10 21:56:29,443 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2024-12-10 21:56:29,443 ] root - INFO - Getting the data from URL
[ 2024-12-10 21:56:29,444 ] root - INFO - Entered initiate_data_ingestion method of Data_Ingestion class
[ 2024-12-10 21:56:29,445 ] root - INFO - Downloading data from https://drive.google.com/file/d/1Bl2r-dnEQzQle8eXc2j6_SNqOCTD18TN/view?usp=sharing into file artifacts\data_ingestion\data.zip
